client_id_to_use = "Google"

[[clients]]
id="Google"
Customer number=1
name="Google inc."
address="""
1600 Amphitheatre Parkway
Mountain View
94043
CA
USA"""

[[clients]]
id="Microsoft"
Customer number=2
name="Microsoft inc."
address="""
Redmond
98052
WA
USA"""

[[clients]]
id="Facebook"
Customer number=3
name="Facebook inc."
address="""
Menlo Park
94025
CA"
USA"""
