# your information
[sender]
company_name = "JD"
personal_name = "John Doe"
address = '''
132, My Street
Bigtown BG23 4YZ
England
'''
phone="+358555555"
email="jd@example.com"
web="https://example.com"
logo_path = "dummy-logo.png"

[bank]
"Bank account"="5555-5555"
"Reg nr"="555555-5555"
"Vat nr"="555555-5555"
IBAN="FI55 5555 5555 5555 5555 5555"
Bic="SWEDSESS"
Comment="Approved for F-tax"

[invoice]
data_dir="exported-from-pta"
balance_file="balance-exp-hledger.csv"
report_file="register-exp-hledger.csv"
logo_path = "dummy-logo.png"
invoice_title = "Invoice"
invoice_date = "2025-06-01"
invoice_number = "321"
due_date = "2025-07-01"
hledger_account_name_for_vat = "liabilities:vat:sales"
hledger_vat_text = "VAT 25% (moms)"
comment = ""
