# your information
[sender]
company_name = "JD"
personal_name = "John Doe"
address = '''
132, My Street
Bigtown BG23 4YZ
England
'''
phone="+358555555"
email="jd@example.com"
web="https://example.com"

[bank]
"Bank account"="5555-5555"
"Reg nr"="555555-5555"
"Vat nr"="555555-5555"
IBAN="FI55 5555 5555 5555 5555 5555"
Bic="SWEDSESS"
Comment="Approved for F-tax"

[invoice]
data_dir=""
data_file="report.reg.json"
logo_path = "dummy-logo.png"
invoice_date = "2025-06-01"
invoice_number = "321"
filter_for_register_report = "Invoice"
account_name_for_amount = "revenue"
account_name_for_vat = "liabilities:vat:sales"
specification_override = ""
