# your information
[sender]
company_name = "JD"
personal_name = "John Doe"
address = '''
132, My Street
Bigtown BG23 4YZ
England
'''
phone="+358555555"
email="jd@example.com"
web="https://example.com"

[bank]
bank_account="Bankaccount: 5555-5555"
reg_nr="Reg nr: 555555-5555"
vat_nr="Vat nr: 555555-5555"
iban="IBAN: FI55 5555 5555 5555 5555 5555"
bic="Bic: SWEDSESS"
comment="Approved for F-tax"

[invoice]
logo_path = "dummy-logo.png"
invoice_date = "2025-06-01"
invoice_number = "321"
filter_for_register_report = "Invoice"
account_name_for_amount = "revenue"
account_name_for_vat = "liabilities:vat:sales"
txn_file="report.reg.json"
specification_override = ""
